---
- hosts: Demo
  user: ansible3
  become: yes
  connection: ssh
  gather_facts: false
#  vars: hi this is i uncoment only for testing
#    docker_image_name: myimg
#    dockerfile_path: /test1/Frontend/
#    docker_image_tag: latest

  tasks:
    - name: Clone repository
      git:
        repo: git@bitbucket.org:WittyIT/witty-ticketing.git
        dest: /home/ansible3/test1
        clone: yes
        version: Docker
        accept_hostkey: yes
        key_file: /home/ansible3/.ssh/id_rsa

#    - name: Install Docker
#      command: apt-get install docker.io -y

#    - name: Run Docker Service
#      command: systemctl enable --now docker

#    - name: Build Image
#      command: docker build -t {{ docker_image_name }}:{{ docker_image_tag }} {{ dockerfile_path }}
#    - name: Docker container Frontend start
#      command: docker run -itd -p 3000:3000 myimg
