
---
- hosts: Demo
  user: ansible1
  become: yes
  connection: ssh
  gather_facts: false
  vars:
    docker_image_name: frontendimg
    dockerfile_path: /home/ansible1/workspace/test1/Frontend
    docker_image_tag: latest

  tasks:
    - name: Clone repository
      git:
        repo: git@bitbucket.org:WittyIT/witty-ticketing.git
        dest: /home/ansible1/test1
        clone: yes
        version: develop
        accept_hostkey: yes
        key_file: /home/ansible1/.ssh/id_rsa

    - name: Install Docker
      command: apt-get install docker.io -y

    - name: Run Docker Service
      command: systemctl enable --now docker

    - name: Permission Allowd
      command: sudo chmod 777 /var/run/*

    - name: Build Image
      command: docker build -t {{ docker_image_name }}:{{ docker_image_tag }} {{ dockerfile_path }}
    - name: Docker container Frontend start
      command: docker run -itd -p 3000:3000 frontendimg
